// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// up_and_out_call_mc
double up_and_out_call_mc(double S0, double K, double B, double sigma, double r, double T, int nSteps, int nPaths, int seed);
RcppExport SEXP _barrierPricer_up_and_out_call_mc(SEXP S0SEXP, SEXP KSEXP, SEXP BSEXP, SEXP sigmaSEXP, SEXP rSEXP, SEXP TSEXP, SEXP nStepsSEXP, SEXP nPathsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type nSteps(nStepsSEXP);
    Rcpp::traits::input_parameter< int >::type nPaths(nPathsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(up_and_out_call_mc(S0, K, B, sigma, r, T, nSteps, nPaths, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_barrierPricer_up_and_out_call_mc", (DL_FUNC) &_barrierPricer_up_and_out_call_mc, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_barrierPricer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
