# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

up_and_out_call_mc <- function(S0, K, B, sigma, r, T, nSteps = 252L, nPaths = 100000L, seed = 123L) {
    .Call(`_barrierPricer_up_and_out_call_mc`, S0, K, B, sigma, r, T, nSteps, nPaths, seed)
}

